[package]
name = "reddit-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
roux = { version = "2.2.3", features = ["blocking"] }
tui = "0.19.0"
